# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Sonos
email: 1292510+svrooij@users.noreply.github.com
# description: >- # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://svrooij.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: svrooij
github_username:  svrooij
repository: svrooij/node-sonos-ts

# Build settings
markdown: kramdown
remote_theme: svrooij/just-the-docs@plausible
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "Sonos on GitHub":
    - "//github.com/svrooij/node-sonos-ts"
  "Become sponsor":
    - "//github.com/sponsors/svrooij/"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2023 Stephan van Rooij. Distributed by an <a href=\"https://github.com/svrooij/node-sonos-ts/tree/master/LICENSE\">MIT license.</a>"

toc:
  max_levels: 2

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Source on Github"
gh_edit_repository: "https://github.com/svrooij/node-sonos-ts" # the github URL for your repo
gh_edit_branch: "master/docs" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

plausible_domain: "sonos.svrooij.io"
